### ISSUE TITLE
authchecker is not applicable for AEM cloud instance

### ISSUE THREAD

**Issue by masumalli** [AdobeDocs/experience-manager-dispatcher.en#64] opened 2023-02-02 17:55 UTC
Issue in ./help/using/permissions-cache.md

This page is applicable to only AMS/on-prem instances, AEM cloud service instances, if the cache is enabled on the secured content, the same page will be cached on fastly CDN, there is no way that the dispatcher can send auth checker request because the request may not even come to the dispatcher. Please add a note message to this page for AEM cloud service customers.

**Comment by raimanS** [comment] 2023-02-03 07:05
Duplicate of issue 56 from the cloud service repo.

**Closed by raimanS** 2023-02-03 07:05 UTC
